### ISSUE TITLE
Select LLM inference provider and merge in code

### ISSUE THREAD

**Issue by jurmy24** [Tanzania-AI-Community/twiga#20]
Select from eg. AWS Bedrock, Azure AI Model Catalog, Groq, or OpenRouter and integrate tool calls, RAG, and chat history manually.

**Comment by jurmy24** [comment]
@fredygerman perhaps you could start taking a look at this issue? Create a new branch from **development** titled username/development/togetherAI.

You can create a free account on Together AI where you get 5 dollars of API credits (we have another account with 50 as well). 

Main file to work from for this would be `app/services/openai_service.py`. I suggest you create a new file in the same folder called `llm_service.py` so its llm agnostic. It's a slightly bigger task than the previous one but will give you a good start to reading the Together AI documentation and replicating the OpenAI assistant. Once you start looking into chat history and the database stuff we can discuss it.

**Comment by fredygerman** [comment]
Alright,  thank you @jurmy24 will get started on this today.

**Comment by jurmy24** [comment]
I took over this issue. Aim to complete today.

**Comment by jurmy24** [comment]
Set up a basic functioning version with Together AI and tool calls with buffer management. Still a few bugs here and there. Will set that as a future issue to solve.
