### ISSUE TITLE
Create a docker-compose for db and server

### ISSUE THREAD

**Issue by jurmy24** [Tanzania-AI-Community/twiga#68]
Within docker/dev/ make it possible to run twiga without setting up your own postgres on your computer. Instead do it in the container.

**Comment by jurmy24** [comment]
@alvaro-mazcu tomorrow I'm hoping to create a makefile that one can run to setup the tables with alembic and automatically add seed data.

**Comment by alvaro-mazcu** [comment]
> @alvaro-mazcu tomorrow I'm hoping to create a makefile that one can run to setup the tables with alembic and automatically add seed data.

https://github.com/Tanzania-AI-Community/twiga/pull/71 😉
